Personal = ('Manuel', 'Lopez',17)
print('\n',Personal)
print('-----------------------------------------------')
print('Nombre:', Personal[0])
print('-----------------------------------------------')
print('Apellido:', Personal[1])
print('-----------------------------------------------')
print('Edad:', Personal[2])
print('-----------------------------------------------')
print('Lopez se encuentra en', Personal.index('Lopez'))
print('-----------------------------------------------')
print('Cantidad de valores en la tupla:', len(Personal))
print('-----------------------------------------------')
