print('⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛')
print('⬛   ** C A R T E L E R A **  ⬛')
print('⬛                            ⬛')
print(f'⬛      Pelicula: {Pelicula}       ⬛')
print(f'⬛     Tanda: {Hora}       ⬛')
print(f'⬛   Combo: {Combo}   ⬛')
print(f'⬛     Precio combo: {P_Combo}      ⬛')
print(f'⬛    Precio entrada: {Ticket}     ⬛')
print('⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛')
print('\n-----------------------------------')